"""create claims table

Revision ID: 0188e8109fe9
Revises: 
Create Date: 2025-04-25 14:27:32.911642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0188e8109fe9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claim',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('grid_id', sa.Integer(), nullable=False),
    sa.Column('claim_type', sa.Enum('CROP', 'LIVESTOCK', name='claimtypeenum'), nullable=False),
    sa.Column('claim_amount', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'AUTHORIZED', 'SETTLED', name='claimstatusenum'), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claim_id'), 'claim', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_claim_id'), table_name='claim')
    op.drop_table('claim')
    # ### end Alembic commands ###
