"""switch status enums to string

Revision ID: 6082c1a9b25d
Revises: 54d1e879ba4c
Create Date: 2025-04-29 08:13:57.255054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6082c1a9b25d'
down_revision: Union[str, None] = '54d1e879ba4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('claim', 'claim_type',
               existing_type=postgresql.ENUM('CROP', 'LIVESTOCK', name='claimtypeenum'),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('claim', 'status',
               existing_type=postgresql.ENUM('PENDING', 'AUTHORIZED', 'SETTLED', name='claimstatusenum'),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('claim', 'status',
               existing_type=sa.String(),
               type_=postgresql.ENUM('PENDING', 'AUTHORIZED', 'SETTLED', name='claimstatusenum'),
               existing_nullable=False)
    op.alter_column('claim', 'claim_type',
               existing_type=sa.String(),
               type_=postgresql.ENUM('CROP', 'LIVESTOCK', name='claimtypeenum'),
               existing_nullable=False)
    # ### end Alembic commands ###
