"""add product table

Revision ID: eb70aaee008f
Revises: 
Create Date: 2025-04-25 07:14:28.145187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb70aaee008f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cps_zone',
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('zone_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('zone_id'),
    sa.UniqueConstraint('zone_name')
    )
    op.create_index(op.f('ix_cps_zone_zone_id'), 'cps_zone', ['zone_id'], unique=False)
    op.create_table('period',
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.Column('period_name', sa.String(length=50), nullable=False),
    sa.Column('date_from', sa.Date(), nullable=False),
    sa.Column('date_to', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('period_id'),
    sa.UniqueConstraint('period_name')
    )
    op.create_index(op.f('ix_period_period_id'), 'period', ['period_id'], unique=False)
    op.create_table('product',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('product_type', sa.Enum('crop', 'livestock', name='producttype'), nullable=False),
    sa.PrimaryKeyConstraint('product_id'),
    sa.UniqueConstraint('product_type')
    )
    op.create_index(op.f('ix_product_product_id'), 'product', ['product_id'], unique=False)
    op.create_table('product_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('elc', sa.Float(), nullable=True),
    sa.Column('trigger_point', sa.Float(), nullable=True),
    sa.Column('exit_point', sa.Float(), nullable=True),
    sa.Column('commission_rate', sa.Float(), nullable=True),
    sa.Column('load', sa.Float(), nullable=True),
    sa.Column('discount', sa.Float(), nullable=True),
    sa.Column('fiscal_year', sa.String(), nullable=True),
    sa.Column('growing_season', sa.String(), nullable=True),
    sa.Column('cps_zone', sa.String(), nullable=True),
    sa.Column('period', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_config_company_id'), 'product_config', ['company_id'], unique=False)
    op.create_index(op.f('ix_product_config_id'), 'product_config', ['id'], unique=False)
    op.create_index(op.f('ix_product_config_name'), 'product_config', ['name'], unique=False)
    op.create_table('growing_season',
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('season_type', sa.String(length=50), nullable=False),
    sa.Column('length', sa.Integer(), nullable=False),
    sa.Column('date_from', sa.Date(), nullable=False),
    sa.Column('date_to', sa.Date(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.product_id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['cps_zone.zone_id'], ),
    sa.PrimaryKeyConstraint('season_id')
    )
    op.create_index(op.f('ix_growing_season_season_id'), 'growing_season', ['season_id'], unique=False)
    op.create_table('ndvi_crop',
    sa.Column('ndvi_id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('growing_season_id', sa.Integer(), nullable=True),
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.Column('index_value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['growing_season_id'], ['growing_season.season_id'], ),
    sa.ForeignKeyConstraint(['period_id'], ['period.period_id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['cps_zone.zone_id'], ),
    sa.PrimaryKeyConstraint('ndvi_id')
    )
    op.create_index(op.f('ix_ndvi_crop_ndvi_id'), 'ndvi_crop', ['ndvi_id'], unique=False)
    op.create_table('trigger_exit_points',
    sa.Column('teid', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.Column('growing_season_id', sa.Integer(), nullable=False),
    sa.Column('trigger_point', sa.Integer(), nullable=False),
    sa.Column('exit_point', sa.Integer(), nullable=False),
    sa.Column('trigger_percentile', sa.Integer(), nullable=False),
    sa.Column('exit_percentile', sa.Integer(), nullable=False),
    sa.Column('elc', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['growing_season_id'], ['growing_season.season_id'], ),
    sa.ForeignKeyConstraint(['period_id'], ['period.period_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.product_id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['cps_zone.zone_id'], ),
    sa.PrimaryKeyConstraint('teid')
    )
    op.create_index(op.f('ix_trigger_exit_points_teid'), 'trigger_exit_points', ['teid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trigger_exit_points_teid'), table_name='trigger_exit_points')
    op.drop_table('trigger_exit_points')
    op.drop_index(op.f('ix_ndvi_crop_ndvi_id'), table_name='ndvi_crop')
    op.drop_table('ndvi_crop')
    op.drop_index(op.f('ix_growing_season_season_id'), table_name='growing_season')
    op.drop_table('growing_season')
    op.drop_index(op.f('ix_product_config_name'), table_name='product_config')
    op.drop_index(op.f('ix_product_config_id'), table_name='product_config')
    op.drop_index(op.f('ix_product_config_company_id'), table_name='product_config')
    op.drop_table('product_config')
    op.drop_index(op.f('ix_product_product_id'), table_name='product')
    op.drop_table('product')
    op.drop_index(op.f('ix_period_period_id'), table_name='period')
    op.drop_table('period')
    op.drop_index(op.f('ix_cps_zone_zone_id'), table_name='cps_zone')
    op.drop_table('cps_zone')
    # ### end Alembic commands ###
